### ISSUE TITLE
Dockerコンテナ化

### ISSUE THREAD

**Issue by massongit** [dev-hato/hato-bot#100]
hato-botをDockerコンテナ化します。

**Comment by nakkaa** [comment]
デメリットってあるのだろうか。Heroku to deployが使えなくなる？

**Comment by Goryudyuma** [comment]
いや別に。今のコードのまま、成果物をDocker imageにするだけ。今まで通りHerokuにもあげられるし、Dockerでも動く感じ。

**Comment by fono09** [comment]
#125 でsetup側はやった。

**Comment by nakkaa** [comment]
これはcloseしても良い？

**Comment by massongit** [comment]
OK
