### ISSUE TITLE
ameshでYahoo APIを使うのをやめる

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#105]
amesh(雨雲画像表示)機能で使っているYahoo!スタティックマップAPIは、
2020年10月31日に提供が終了する。
https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/static.html

それまでに同等の機能を別の方法で実現する必要がある。

**Comment by massongit** [comment]
Yahoo側で案内している移行先を軽くみた限りではMapboxが良さげ？
https://www.mapbox.jp/yolp

**Comment by massongit** [comment]
https://docs.mapbox.com/jp/yolp-to-mapbox/static/#yolp%E3%81%A8%E4%B8%BB%E3%81%AA%E9%81%95%E3%81%84

```
雨雲レーダーは対応できません。
```

つらい

**Comment by massongit** [comment]
気象庁のHPをスクレイピング......？

**Comment by massongit** [comment]
ameshの実装はこの辺り。
https://github.com/dev-hato/hato-bot/blob/479f4889e41a7e53e51304b70d8f7c0c0c30129f/plugins/hato.py#L147-L197

処理の流れは以下のようになっている。
* 入力された地名を元に緯度, 経度を導出
* 緯度, 経度を指定して雨雲付き地図画像生成 (Yahoo!スタティックマップAPI使用)
* 画像をSlackに投稿

**Comment by m77so** [comment]
## 気象庁雨雲レーダー調査

現在入手可能な時刻情報．何時に生成された情報かと，何時の予報・観測かという２つの時刻が入っている
https://www.jma.go.jp/bosai/jmatile/data/nowc/targetTimes_N1.json

このタイル座標で画像が乗っている
https://maps.gsi.go.jp/development/tileCoordCheck.html#10/35.5054/139.8621
