### ISSUE TITLE
ameshのヘルプ説明文をわかりやすくする

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#106]
`@hato help` したときに `amesh ... ameshを表示する` という説明文が出るが、
`amesh ... amesh(雨雲情報)を表示する` に書き換える。

(初見の人はameshが何かわからないかもしれないため)

**Comment by Goryudyuma** [comment]
長い。コマンドとして `@hato 雨雲情報を表示する 東京` とか打ちたいか？絶対typo量産する。

**Comment by Goryudyuma** [comment]
「雨」一文字か、「雨雲」くらいが良いのでは？

**Comment by nakkaa** [comment]
言葉が足りなかった。
コマンドは変更なしで `amesh` のままのつもりだった。(またはもっと短い表記方法もオプションとして用意するか。)
ここで伝えたかったのは、 `@hato help` したときに `amesh ... ameshを表示する` という説明文が出るけど、 `amesh ... amesh(雨雲情報)を表示する` に書き換えた方が初見でもわかりやすいかなっていうコメントです。

**Comment by Goryudyuma** [comment]
あーなるほど。じゃあ最短で言うと、helpの修正だけで事足りるね。
