### ISSUE TITLE
レビュー作業を楽にしたい

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#107]
PRのレビュー時に本体(plugin, library配下のpyファイル)に変更がある場合は以下の手順で動作確認を行っているがもう少し手間を減らしたい。

1. PRのブランチをローカルへcheckoutする。
2. pipenv install する
3. docker-compose up -dする
4. create tableする(よくし忘れて焦るので自動化したい)
5. botを起動する
6. 一通りの機能を確認する。実行するコマンドは以下のとおり。
    * text, text add, text delete
    * in, rida
    * amesh, eq, 天気
7. 問題がなければdevelopにマージする。

改修箇所によって手順をスキップしても問題ない部分はスキップすべきか。。。？
上記を実装者にお願いすれば済む気がするなあ。

**Comment by Goryudyuma** [comment]
4は終わってる
