### ISSUE TITLE
鳩botをWindowsで動かす方法をWikiに作成する

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#109]
UbuntuやMacで動かす手順は書いているが、Windowsで動かす手順書がないので作成する
https://github.com/nakkaa/hato-bot/wiki

**Comment by Goryudyuma** [comment]
WSL2で動くよ。何なら僕はWSL2でしかhatobot触ったこと無いよ。

**Comment by nakkaa** [comment]
* WSL2を使う。(Windows10 Version 2004が必要になる)

**Comment by nakkaa** [comment]
動かさないのでcloseする。
