### ISSUE TITLE
新しいSlack API Tokenに対応する

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#127]
今の鳩botは https://github.com/nakkaa/hato-bot/issues/124 みたいにTokenの発行に手間がかかるので、新tokenに対応したい。 (old tokenは使うのをやめたい。)

**Comment by Goryudyuma** [comment]
やっぱこれ厳しそう、ユーザーがなんか打ったやつを、今はRTMを使って受け取ってるけど、RTMがClassic APIにしかない。新APIでは、POSTされるのでその先でサーバーで待ち構えて捉えるっぽい。
hato-botをweb app化して、herokuのリンクを入れれば可能っちゃ可能だけど、デバッグがめんどくさくなりそう？
やる？

**Comment by nakkaa** [comment]
今のbotの作りはRTMを使っているとはいえ、常にslackのメッセージを監視しているわけではないので
新API方式の Slack --(postリクエスト)--> サーバ(bot) にしても不都合はないかな。

サーバ(bot)に対するPOSTリクエストとレスポンスのチェックをするならシナリオテストしやすそうだなとか思ったり。

> デバッグがめんどくさくなりそう？
これはあまりピントきていない。
