### ISSUE TITLE
パワーワードを登録したユーザをJoin文で取ってくる実装を入れる

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#137]
https://twitter.com/poc_popoyama/status/1271081872492122113?s=20

**Comment by Goryudyuma** [comment]
ちゃんと正規化してね。

**Comment by nakkaa** [comment]
ユーザ名とidを登録するテーブルが必要になる。
パワーワードテーブルにidを格納する列が必要になる。
マイグレどうやるんだろ。

**Comment by nakkaa** [comment]
廃止するのでclose
