### ISSUE TITLE
Ameshのファイル名が同じなので、連続してameshのリクエストを送ると、タイミングによってはファイルが消えている

### ISSUE THREAD

**Issue by Goryudyuma** [dev-hato/hato-bot#147]
リクエスト1がameshから画像を取得
リクエスト1がslackに送る
リクエスト2がameshから画像を取得
リクエスト1が画像を削除する
リクエスト2が、画像がなくてエラーになる

ファイル名をユニークにすればよい

**Comment by massongit** [comment]
タイムスタンプ付与が手っ取り早そう

**Comment by massongit** [comment]
ameshの画像データは保存する必要がないので、 `tempfile.TemporaryFile` を使えば解決しそうです。
https://hibiki-press.tech/python/tempfile-md/2829

**Comment by massongit** [comment]
https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/static.html

リクエストパラメーターとして `output` を指定しないとPNG形式で画像が返ってくるため、現状ではPNG形式で画像が返ってきています。
しかし、ファイル名は `amesh.jpg` となっているため、実際の形式とファイル名が異なっているという問題があります。
この問題についても、 `tempfile.NamedTemporaryFile` を使うことで解決しそうです。
