### ISSUE TITLE
discord対応

### ISSUE THREAD

**Issue by Goryudyuma** [dev-hato/hato-bot#154]
いる？
新SlackAPIのPRで、チャット側を完全に依存を切ったおかけで、できなくはないと思う。必要ならやる。

**Comment by Goryudyuma** [comment]
websocketで常時稼働させる形式なので、料金体系が心配。
herokuは24時間一台を動かし続けても無料
月1000時間まで無料なので
ただし二台以上動かそうとすると、無料枠を超えて突然止まる。

**Comment by Goryudyuma** [comment]
Discordのtokenがある場合のみDiscordからのメッセージを取得する、はできるっぽい
(tokenのあるなしで判定)

Slackは必須機能？今の作りだと、Slackを無効化って難しくない？

**Comment by domishana** [comment]
ずっとROMっていたけれどdiscordまわりは少しお手伝いできるかもです

**Comment by domishana** [comment]
pythonでdiscord触る上でのデファクトは[discord.py](https://discordpy.readthedocs.io/ja/latest/)かなぁと思います。
これ使わないなら直でdiscordのAPIを叩くとかになりそう。

https://github.com/dev-hato/hato-bot/issues/154#issuecomment-650744427
これの気にしているところはいまいち理解しきれていないけれど、単一のスクリプトを実行したときにslack, discord両方動かすにはどうすればってところですかね

**Comment by Goryudyuma** [comment]
全部お任せします〜

slackの方は新APIの方に移ったので、全部Event Subscriptionsなどで構成され、リクエストがあればherokuが起動し、なければ寝てる、みたいな状態になってます。
discordのAPIってwebsocketが多かった覚えがあって、そしたら常時起動しっぱなしだなぁって思ったんですけど、1台くらいなら特に問題はないね、といった趣旨です。

slackとdiscordを両方同時に動かす方式でもいいし、confでswitchさせる形式でも良いです。
ただ、両方設定しないと動かないのは、ちょっとややこしくなるのでやめた方がいいかな？

**Comment by nakkaa** [comment]
Slack/Discord のTokenが設定されてる方の機能が有効になった方が自然かな。
片方だけなら片方が、両方とも設定されていれば両方の機能が有効になる感じ。

**Comment by domishana** [comment]
> slackの方は新APIの方に移ったので、全部Event Subscriptionsなどで構成され、リクエストがあればherokuが起動し、なければ寝てる、みたいな状態になってます。
なるほどです。知らなかった。discordの場合は基本的に常時heroku起動してる状態になるという認識でよいと思います。
