### ISSUE TITLE
linear historyを強制する

### ISSUE THREAD

**Issue by Goryudyuma** [dev-hato/hato-bot#157]
https://help.github.com/ja/github/administering-a-repository/requiring-a-linear-commit-history
今の設定だと、developに入った時点でテストが落ちる可能性があると思う

**Comment by nakkaa** [comment]
設定はした。が、直線状のコミット履歴ってなんぞ。。。

**Comment by Goryudyuma** [comment]
枝分かれした後のマージができなくなる、と思うんだけど・・・。ちゃんと動くかわからないし、まあ動いたらいいね、的な。
