### ISSUE TITLE
僕か鳩(もしくは両方)にリポジトリのAdmin権限つけてくれない？

### ISSUE THREAD

**Issue by Goryudyuma** [dev-hato/hato-bot#168]
リポジトリの設定をいじるの、現状なっかあちゃんで待ちが発生しているので。
多少早くなる、って程度なので、別になくても困ってる訳ではないです。

**Comment by Goryudyuma** [comment]
https://github.com/nakkaa/hato-bot/issues/157
具体的にはこれとか止まってるので

**Comment by nakkaa** [comment]
Admin権限付与って有料プランに加入しないとできなかったりする？
(設定を見て回ったが、そんな項目がなさそうで)

**Comment by nakkaa** [comment]
organizationすることで解決
