### ISSUE TITLE
前回のリリース時にmasterにマージしたとき？に他のPRが閉じられてた問題

### ISSUE THREAD

**Issue by Goryudyuma** [dev-hato/hato-bot#185]
https://github.com/dev-hato/hato-bot/blob/develop/.github/workflows/pr-test.yml#L90
どこかにバグありそう

**Comment by massongit** [comment]
誤ってクローズされたPR: https://github.com/dev-hato/hato-bot/pull/184, https://github.com/dev-hato/hato-bot/pull/141

**Comment by massongit** [comment]
クローズの原因となったと思しきPR: https://github.com/dev-hato/hato-bot/pull/184, https://github.com/dev-hato/hato-bot/pull/183
