### ISSUE TITLE
天気機能の廃止(livedoor天気予報終了)

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#189]
鳩botの `天気` 機能で使っている[天気予報 きょうの気象情報 - livedoor 天気情報](http://weather.livedoor.com/)のサービスが7月31日に終了するため、天気機能が使えなくなる。

よって、機能の廃止or別サービスAPIに移行する必要がある。

**Comment by Goryudyuma** [comment]
代替サービスの候補はある？

**Comment by nakkaa** [comment]
まだ調べられてないのでそこからですね。

https://qiita.com/cnakano/items/ff3fd90f685f4ca363cc

**Comment by Goryudyuma** [comment]
じゃあとりあえず廃止かな〜、しゃーないね
