### ISSUE TITLE
おみくじ機能の確率調整

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#2025]
揚げ吉が出づらいので出やすくしたい

**Comment by fono09** [comment]
内部的にはやってそうだけど `random.seed()` を呼んだほうが良いかもしれない

**Comment by fono09** [comment]
あと、日替わりにする場合は `radom.seed(user_name + date.strftime("%F"))` かな

**Comment by fono09** [comment]
日替わりは別チケットにする。
シードアルゴリズムをOmikujiライブラリ側で変更可能にしないといけない。

**Comment by fono09** [comment]
#3716  おみくじ日替わりはこっちにした
