### ISSUE TITLE
docker hubにimageをおきたい

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#400]
docker buildするときにパッケージがなくてビルドできない悲しみから解き放たれたい

**Comment by massongit** [comment]
docker hubに置く？

**Comment by nakkaa** [comment]
そうだね。リリースしたらdocker hubに置きたい。

**Comment by bgpat** [comment]
やること

- [ ] Docker Hub の org を作る @dev-hato/owner
- [ ] リリース時に Docker Hub に push する CI を追加する
     Docker Hub 上で ![image](https://user-images.githubusercontent.com/6045753/94996394-6b3df300-05df-11eb-8eae-68b7c7cb24eb.png) みたいな設定を書くと実現できる

**Comment by bgpat** [comment]
どうぞ作ってということだったので作る
![image](https://user-images.githubusercontent.com/6045753/94997657-96c4db80-05e7-11eb-8ffb-66354d890359.png)

https://hub.docker.com/subscription?plan=team&paid=false
![image](https://user-images.githubusercontent.com/6045753/94997678-ab08d880-05e7-11eb-9b40-fed2396c98cd.png)

**Comment by bgpat** [comment]
分かる範囲でメンバーを追加していく

@nakkaa 
![image](https://user-images.githubusercontent.com/6045753/94997788-5b76dc80-05e8-11eb-9c66-3bad5b6bc494.png)

@massongit 見つからなかった
![image](https://user-images.githubusercontent.com/6045753/94997794-67fb3500-05e8-11eb-9e7a-3d00ac35cdd2.png)

@Goryudyuma 
![image](https://user-images.githubusercontent.com/6045753/94997808-88c38a80-05e8-11eb-8926-d865e5a91528.png)

4人目を追加しようとしたら Add ボタンが disabled になっていた
free plan は 3人までしかメンバーを設定できないらしい
![image](https://user-images.githubusercontent.com/6045753/94997825-aabd0d00-05e8-11eb-9600-052e4ecd5b0b.png)

設定終われば自分は見れなくてもいいと思うのでいい感じに変更してほしい

**Comment by bgpat** [comment]
GitHub repo とリンクさせる
https://hub.docker.com/orgs/devhato/settings/linked-accounts
![image](https://user-images.githubusercontent.com/6045753/94997977-aba26e80-05e9-11eb-8621-1e0ae031fb83.png)

repository を作る => 権限が足りなかった
dev-hato の GitHub org と連携させるには organization の owner である必要があるのかも？
![image](https://user-images.githubusercontent.com/6045753/94998038-1b185e00-05ea-11eb-8bde-8ce8113c867a.png)

**Comment by bgpat** [comment]
@Goryudyuma 権限渡したのであとは任せたいです :+1:

**Comment by bgpat** [comment]
![image](https://user-images.githubusercontent.com/6045753/94998220-28821800-05eb-11eb-8691-7962db2dc6b4.png)
![image](https://user-images.githubusercontent.com/6045753/94998217-23bd6400-05eb-11eb-888c-489b63fc9c08.png)

**Comment by bgpat** [comment]
GitHub Packages でもいいのでは？

**Comment by nakkaa** [comment]
Githubでもいいなぁ

**Comment by massongit** [comment]
hato-atamaで既にそういうCI構築されているので、それを流用すれば良さそう
