### ISSUE TITLE
Pipfile の更新 PR で CI が動くようにする

### ISSUE THREAD

**Issue by bgpat** [dev-hato/hato-bot#423]
## Why

Pipfile を更新する GitHub Actions workflow が存在していて PR を自動で作ってくれるが、 CI が実行されず merge ができない。
現状は #422 のように手動で PR を作って対応している。

> * #420, #421 はCIによって生成される
> * #420, #421 はdevelopにマージされるものなので、CIが通らないとマージできない
> * CIの連鎖が起きないようになっているため、 #420, #421 が作成されてもCIが走らずマージできない
> 
> という理由で直接mergeしない (できない) わけです。

_Originally posted by @massongit in https://github.com/dev-hato/hato-bot/pull/422#issuecomment-703124658_

## What

Pipfile 更新 PR でも CI が動くようにする

**Comment by bgpat** [comment]
`workflow_dispatch` を使えば GItHub Actions から別の workflow を実行できるらしいので試してみたい
https://docs.github.com/ja/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch

**Comment by bgpat** [comment]
GHA の token を使わなければいいだけなので GitHub App を作るのでもいい

**Comment by massongit** [comment]
https://github.com/dev-hato/hato-bot/blob/5510719670b97718282a5d11ef4e35b4c384ca12/Pipfile#L46

現在はmasterで固定になっているため、更新する必要がなくなっている。
