### ISSUE TITLE
linterを手元開発環境で確認できるようにしたい

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#875]

**Comment by itsumomomadoka** [comment]
これマジで必要
だれかドキュメント整備員やってくれてもいいのよ

**Comment by massongit** [comment]
割とガバく書いてもCIが怒ってくれるやろというCIでどうにかする運用でやってきた弊害だなぁ。

**Comment by massongit** [comment]
textlintについては `package.json` でコマンドを定義可能なので、そこでsuper-linterと同様のコマンドを定義してやれば良いのだろうとは思う。

**Comment by massongit** [comment]
`yarn run lint` すればある程度のlintがかかるようにしたので確認してもらえると (詳しい手順はREADME参照)。

**Comment by massongit** [comment]
開発環境でのlinterって任意のタイミングでかけられた方がうれしい？
もしコミット時だけでいいなら、pre-commitに寄せれるものは寄せても良いのかなという気がしている (gitleaksは元々コミット時に実行されるようになってる)。
