### ISSUE TITLE
「amesh 地名」で地名の雨雲情報を出すようにしたい

### ISSUE THREAD

**Issue by nakkaa** [dev-hato/hato-bot#97]

**Comment by Goryudyuma** [comment]
```
そうだね。
前提だけどamesh と 天気コマンドは別物なのよね
ameshは東京の雨雲画像を取ってくる(Yahoo API)
天気コマンドは県庁所在地の天気情報を文字でとってくる(ライブドアのAPI)
今回はameshを東京以外にも対応したい。
```
https://carbonfriend.slack.com/archives/CMJ1CQT5H/p1590721892160700?thread_ts=1590584883.154900&cid=CMJ1CQT5H

**Comment by massongit** [comment]
Yahoo!ジオコーダAPI を使うと良さそう
https://developer.yahoo.co.jp/webapi/map/openlocalplatform/v1/geocoder.html
